{
  "hoistedDependencies": {},
  "hoistPattern": [
    "*"
  ],
  "included": {
    "dependencies": true,
    "devDependencies": true,
    "optionalDependencies": true
  },
  "layoutVersion": 5,
  "nodeLinker": "isolated",
  "packageManager": "pnpm@12.6.0",
  "pendingBuilds": [],
  "prunedAt": "Sun, 27 Sep 2026 18:40:03 GMT",
  "publicHoistPattern": [],
  "skipped": [],
  "storeDir": "C:\\Users\\acer\\AppData\\Local\\pnpm\\store\\v11",
  "virtualStoreDir": "C:\\Users\\acer\\Downloads\\AI-Comic-Creator-Extracted\\node_modules\\.pnpm",
  "virtualStoreDirMaxLength": 60,
  "allowBuilds": {}
}